// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTokenApiV1TokensPost, helloApiV1HelloGet, type Options, readMeApiV1MeGet } from '../sdk.gen';
import type { CreateTokenApiV1TokensPostData, CreateTokenApiV1TokensPostError, CreateTokenApiV1TokensPostResponse, HelloApiV1HelloGetData, HelloApiV1HelloGetResponse, ReadMeApiV1MeGetData, ReadMeApiV1MeGetResponse } from '../types.gen';

/**
 * Create Token
 *
 * Create an access token for a valid user.
 */
export const createTokenApiV1TokensPostMutation = (options?: Partial<Options<CreateTokenApiV1TokensPostData>>): UseMutationOptions<CreateTokenApiV1TokensPostResponse, CreateTokenApiV1TokensPostError, Options<CreateTokenApiV1TokensPostData>> => {
    const mutationOptions: UseMutationOptions<CreateTokenApiV1TokensPostResponse, CreateTokenApiV1TokensPostError, Options<CreateTokenApiV1TokensPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTokenApiV1TokensPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const readMeApiV1MeGetQueryKey = (options?: Options<ReadMeApiV1MeGetData>) => createQueryKey('readMeApiV1MeGet', options);

/**
 * Read Me
 *
 * Return the currently authenticated user.
 */
export const readMeApiV1MeGetOptions = (options?: Options<ReadMeApiV1MeGetData>) => queryOptions<ReadMeApiV1MeGetResponse, DefaultError, ReadMeApiV1MeGetResponse, ReturnType<typeof readMeApiV1MeGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readMeApiV1MeGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readMeApiV1MeGetQueryKey(options)
});

export const helloApiV1HelloGetQueryKey = (options?: Options<HelloApiV1HelloGetData>) => createQueryKey('helloApiV1HelloGet', options);

/**
 * Hello
 */
export const helloApiV1HelloGetOptions = (options?: Options<HelloApiV1HelloGetData>) => queryOptions<HelloApiV1HelloGetResponse, DefaultError, HelloApiV1HelloGetResponse, ReturnType<typeof helloApiV1HelloGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await helloApiV1HelloGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: helloApiV1HelloGetQueryKey(options)
});
