// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTokenApiV1TokensPostData, CreateTokenApiV1TokensPostErrors, CreateTokenApiV1TokensPostResponses, HelloApiV1HelloGetData, HelloApiV1HelloGetResponses, ReadMeApiV1MeGetData, ReadMeApiV1MeGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create Token
 *
 * Create an access token for a valid user.
 */
export const createTokenApiV1TokensPost = <ThrowOnError extends boolean = false>(options: Options<CreateTokenApiV1TokensPostData, ThrowOnError>) => (options.client ?? client).post<CreateTokenApiV1TokensPostResponses, CreateTokenApiV1TokensPostErrors, ThrowOnError>({
    url: '/api/v1/tokens',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Me
 *
 * Return the currently authenticated user.
 */
export const readMeApiV1MeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadMeApiV1MeGetData, ThrowOnError>) => (options?.client ?? client).get<ReadMeApiV1MeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/me',
    ...options
});

/**
 * Hello
 */
export const helloApiV1HelloGet = <ThrowOnError extends boolean = false>(options?: Options<HelloApiV1HelloGetData, ThrowOnError>) => (options?.client ?? client).get<HelloApiV1HelloGetResponses, unknown, ThrowOnError>({ url: '/api/v1/hello/', ...options });
