// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HelloApiV1HelloGetResponse } from './types.gen';

export class HelloService {
    /**
     * Hello
     * @returns HelloResponse Successful Response
     * @throws ApiError
     */
    public static apiV1HelloGet(): CancelablePromise<HelloApiV1HelloGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/hello/'
        });
    }
    
}