// This file is auto-generated by @hey-api/openapi-ts

/**
 * HelloResponse
 */
export type HelloResponse = {
    /**
     * Message
     */
    message: string;
};

export type HelloApiV1HelloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/hello/';
};

export type HelloApiV1HelloGetResponses = {
    /**
     * Successful Response
     */
    200: HelloResponse;
};

export type HelloApiV1HelloGetResponse = HelloApiV1HelloGetResponses[keyof HelloApiV1HelloGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
