// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HelloResponse
 *
 * Return the hello endpoint payload.
 */
export type HelloResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * TokenCreateRequest
 *
 * Request body for creating an access token.
 */
export type TokenCreateRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * TokenResponse
 *
 * Response body for an access token.
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserResponse
 *
 * Public representation of a user.
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type CreateTokenApiV1TokensPostData = {
    body: TokenCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tokens';
};

export type CreateTokenApiV1TokensPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTokenApiV1TokensPostError = CreateTokenApiV1TokensPostErrors[keyof CreateTokenApiV1TokensPostErrors];

export type CreateTokenApiV1TokensPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type CreateTokenApiV1TokensPostResponse = CreateTokenApiV1TokensPostResponses[keyof CreateTokenApiV1TokensPostResponses];

export type ReadMeApiV1MeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type ReadMeApiV1MeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ReadMeApiV1MeGetResponse = ReadMeApiV1MeGetResponses[keyof ReadMeApiV1MeGetResponses];

export type HelloApiV1HelloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/hello/';
};

export type HelloApiV1HelloGetResponses = {
    /**
     * Successful Response
     */
    200: HelloResponse;
};

export type HelloApiV1HelloGetResponse = HelloApiV1HelloGetResponses[keyof HelloApiV1HelloGetResponses];
